// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fckxdhwrwpftcrckuwos.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZja3hkaHdyd3BmdGNyY2t1d29zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODgwNTYsImV4cCI6MjA2MjU2NDA1Nn0.Z2w4FtjLYxkobqxf9Gzevxwsw1ylaUDLKZ6C__H3Koc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);